name: Linting

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '30 5 * * *'

jobs:
  Linting:
    name: Linting

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort

      - name: Check sorted python imports using isort
        run: isort . -c

      - name: Lint code with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          
          # General linting with flake8
          flake8 . --count --max-complexity=30 --max-line-length=127 --statistics
          
          # Check for cyclomatic complexity for specific files
          flake8 dice_ml/data_interfaces/ --count --max-complexity=10 --max-line-length=127
  